### ISSUE TITLE
Homey looses connection with iKettle 2.0 over time

### ISSUE THREAD

**Issue by jghaanstra** [athombv/am.smarter#10]
**What is your Homey version (Settings → System)?**
Homey firmware 1.2.0 RC9 | Smarter app 2.0.7 | iKettle firmware 1.9

**What did you try to achieve?**
Control the iKettle using Homey, either through it's action cards or using the toggle on the device card.

**Please include detailed steps how we can reproduce the issue**
Add the iKettle 2.0 as device in Homey. It works after initial pairing. Wait for some time and Homey will loose the connection with the iKettle resulting in Homey not being able to control the kettle, not through any flow but also not through the device card.

**What was the result?**
Homey cant control the iKettle, no errors are shown in the browser console. I can toggle the device and it shows as toggled on/off but the iKettle never responds. My iKettle has a static IP address and can be controlled through the Smarter app without any issues.

**What did you expect as result?**
That Homey can control the iKettle at any time, not just only shortly pairing the device or rebooting Homey.

**Any other remarks**
It seems the settings of the iKettle are saved until it looses connection. So the water level and temperature remain on the value at the moment the connection was lost. This for instance results in the condition card for "iKettle water level is not empty" to trigger as true while the kettle could actually be empty.

[EDIT]
I noticed the Smarter app crashed after trying to toggle the iKettle. I restarted automatically so I was unable to copy the error but it said something about a timeout. I did send a log afterwards: BEFF492B73

**Comment by jghaanstra** [comment]
This might be a duplicate of https://github.com/athombv/am.smarter/issues/6

Seems to be the same error I receive when Homey looses connection.

**Comment by konradwalsh** [comment]
Rather than opening another issue.. I can confirm that whenever Homey reboots, I have an Offline iKettle. If go to apps / smarter / restart app it works fine till the next homey reboot

**Comment by sizarkamar** [comment]
I can confirm this bug, I have exactly the same issue as jghaanstra

**Comment by sizarkamar** [comment]
Any update on this issue? Can we expect that it will be fixed soon?

**Comment by konradwalsh** [comment]
Its not a solution but a workaround that works for me is use the Candy app to restart the Smarter app every 15 mins.

**Comment by sizarkamar** [comment]
thank you konradwalsh, but it didn't work for me, after restart of the app the iKettle goes offline.
I think also that my problem is different than yours, because for me it's only working short after pairing and after that the iKettle goes offline/can't control it anymore, as original started by jghaanstra.
I hope the bug will be fixed soon.

**Comment by jghaanstra** [comment]
Restarting the app does solve my issue, the connection works for some time again and than it's lost again. The app has been rewritten with SDK2 and I'm guessing they will release the update once Homey firmware 1.5 goes to the stable channel. Let's see if that fixes this issue.

**Comment by WoutervdBrink** [comment]
Hi there, I developed the SDKv2 app. The app is currently going through QA and should be released soon enough.

As for the connection issues: the new app tries to fix them. Whenever a Smarter device does not give us an update on its state for 20 seconds, it closes the connection and tries to re-discover it, based on the MAC-address. This should fix the connection issues.

When the app is released, could you please let me know if it fixes the issue?

**Comment by sizarkamar** [comment]
I can't wait to test the new app version.
For sure I'll let you know if it fixed the issue.

**Comment by RobinBol** [comment]
This should be fixed in the beta version of the Smarter app, could you test it and let me know if this resolves your issue?

**Comment by sizarkamar** [comment]
Hi Robin, thabk you for all your effort. I tested the beta version and I still have the same issue, it disconnect from the kettle in less than 30 minutes.
By the way I like very much the new mobile card.

**Comment by jghaanstra** [comment]
@RobinBol thanx for the beta update. I was using a CLI install of the SDK2 version of the app by Wouter which had already fixed my issue. I'd like to close this issue but since @sizarkamar is still experiencing this issue I'll leave it open for further discussion. While testing I did discover another bug though but I'll report it as a seperate issue.

@sizarkamar when your iKettle become unreachable, can you still control it using the mobile app from Smarter?

**Comment by sizarkamar** [comment]
@jghaanstra yes my kettle is always reachable from the Smarter app

**Comment by RobinBol** [comment]
@sizarkamar I made some fixes to the beta app in the meantime, not sure if these were also in the beta app when you tested them. Could you update the app to the latest beta (v3.0.2) and let me know if the issue persists? If so, could you send me an application log (Settings > Apps, click the white space around an app item, hold alt and click the send log to developer link)? Application logs are only available in the latests Homey firmware beta build (1.5.4-rc.1 and up).

**Comment by sizarkamar** [comment]
@RobinBol I update it to the new beta and I have still the same problem. I send you the application log. I also start to think that maybe I have a faulty iKettle, since it's working for everyone.
Thank you for all your effort.

**Comment by RobinBol** [comment]
@sizarkamar Thanks! (next time mention the log id please, I did manage to find it anyway) It seems the iKettle is indeed faulty or there is something wrong with your wifi network. Maybe your router disables udp broadcasting? Anyway, it just doesn't seem to respond to the discovery queries send by Homey.

I think I'll close this issue as it seems to be solved for the creater, sorry I can't help you further @sizarkamar
